services:
  db:
    image: postgres:18-alpine
    env_file:
      - "./env/postgres.env"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./backend/tests/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    ports:
      - "8100:8100"
    env_file:
      - "./env/postgres.env"
      - "./env/app.env"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_MOCKING=disabled
      - VITE_API_BASE_URL=http://localhost:8100
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pg_data:
