# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: link_queries.sql
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from src.db import models


CREATE_LINK = """-- name: create_link \\:one
INSERT INTO links (creator_id, original_url, short_code)
VALUES (:p1, :p2, :p3)
RETURNING id, creator_id, original_url, short_code, created_at, is_active, is_deleted
"""


GET_LINK_BY_CODE = """-- name: get_link_by_code \\:one
SELECT id, creator_id, original_url, short_code, created_at, is_active, is_deleted FROM links
WHERE short_code = :p1 AND is_deleted = false
LIMIT 1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_link(self, *, creator_id: int, original_url: str, short_code: str) -> Optional[models.Link]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_LINK), {"p1": creator_id, "p2": original_url, "p3": short_code})).first()
        if row is None:
            return None
        return models.Link(
            id=row[0],
            creator_id=row[1],
            original_url=row[2],
            short_code=row[3],
            created_at=row[4],
            is_active=row[5],
            is_deleted=row[6],
        )

    async def get_link_by_code(self, *, short_code: str) -> Optional[models.Link]:
        row = (await self._conn.execute(sqlalchemy.text(GET_LINK_BY_CODE), {"p1": short_code})).first()
        if row is None:
            return None
        return models.Link(
            id=row[0],
            creator_id=row[1],
            original_url=row[2],
            short_code=row[3],
            created_at=row[4],
            is_active=row[5],
            is_deleted=row[6],
        )
