# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import dataclasses
import datetime
from typing import Optional


@dataclasses.dataclass()
class Click:
    id: int
    link_id: int
    user_agent: Optional[str]
    referred_from: Optional[str]
    ip_address: Optional[str]
    clicked_at: datetime.datetime


@dataclasses.dataclass()
class Link:
    id: int
    creator_id: int
    original_url: str
    short_code: str
    created_at: datetime.datetime
    is_active: bool
    is_deleted: bool


@dataclasses.dataclass()
class User:
    id: int
    nickname: str
    email: str
    password: memoryview
    created_at: datetime.datetime
    is_deleted: bool
