# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: user_quieries.sql
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from db import models


CREATE_USER = """-- name: create_user \\:one
INSERT INTO users (nickname, email, password)
VALUES (:p1, :p2, :p3)
RETURNING id, nickname, email, password, created_at, is_deleted
"""


GET_USER_BY_EMAIL = """-- name: get_user_by_email \\:one
SELECT id, nickname, email, password, created_at, is_deleted FROM users WHERE email = :p1 LIMIT 1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_user(self, *, nickname: str, email: str, password: memoryview) -> Optional[models.User]:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_USER), {"p1": nickname, "p2": email, "p3": password})).first()
        if row is None:
            return None
        return models.User(
            id=row[0],
            nickname=row[1],
            email=row[2],
            password=row[3],
            created_at=row[4],
            is_deleted=row[5],
        )

    async def get_user_by_email(self, *, email: str) -> Optional[models.User]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER_BY_EMAIL), {"p1": email})).first()
        if row is None:
            return None
        return models.User(
            id=row[0],
            nickname=row[1],
            email=row[2],
            password=row[3],
            created_at=row[4],
            is_deleted=row[5],
        )
